### ISSUE TITLE
缺少陳怡潔委員資訊

### ISSUE THREAD

**Issue by myjian** [g0v/ly-tel#7]
照片：http://www.ly.gov.tw/upload/01_introduce/0103_leg/LGpicture/81115.jpg
陳怡潔  親民黨  全國不分區

國會研究室
電話：02-2358-6798
傳真：02-2358-6800
地址：10051台北市中正區濟南路一段3-1號507室

資料來源：
http://www.ly.gov.tw/03_leg/0301_main/legIntro.action?stage=8&lgno=00115

**Comment by billy3321** [comment]
已更新至第九屆，感謝指正！

https://github.com/g0v/ly-tel/commit/fe25687ffc25494e5731cec728bc31991664a955
